import { type KeyboardEvent, useState } from 'react';
import { CodeEditor } from '../common/CodeEditor';
import './JsonToTs.css';

type CopyStatus = 'idle' | 'copied' | 'failed';

const SAMPLE_JSON = `{
  "id": 1,
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
  "active": true,
  "skills": ["TypeScript", "Golang", "React"],
  "address": {
    "street": "456 Market St",
    "city": "San Francisco",
    "zip": "94103"
  },
  "roles": [
    { "roleId": "admin", "permissions": ["read", "write"] },
    { "roleId": "billing", "permissions": ["read"] }
  ]
}`;

interface TsField {
  name: string;
  type: string;
  optional: boolean;
}

interface TsInterfaceDefinition {
  name: string;
  fields: TsField[];
}

function convertJsonToTypeScript(
  jsonStr: string,
  rootName: string = 'AutoGenerated',
  useTypeAlias: boolean = false,
  useOptional: boolean = true,
  useInlineTypes: boolean = false,
): { code: string; error?: string } {
  try {
    const trimmed = jsonStr.trim();
    if (!trimmed) {
      return { code: '' };
    }
    const parsed = JSON.parse(trimmed);

    const interfaces: TsInterfaceDefinition[] = [];
    const interfaceNames = new Set<string>();

    const toPascalCase = (str: string) => {
      const cleaned = str.replace(/[^a-zA-Z0-9_]/g, '_');
      return cleaned
        .split(/[_\s-]+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('') || 'Field';
    };

    const singularize = (name: string): string => {
      let sing = name;
      if (sing.endsWith('ies')) sing = sing.slice(0, -3) + 'y';
      else if (sing.endsWith('ses')) sing = sing.slice(0, -2);
      else if (sing.endsWith('s') && !sing.endsWith('ss')) sing = sing.slice(0, -1);
      return sing;
    };

    const mainName = toPascalCase(rootName || 'AutoGenerated');
    interfaceNames.add(mainName);

    const getUniqueName = (baseName: string): string => {
      let name = toPascalCase(singularize(baseName));
      if (!name) name = 'Interface';
      if (name === mainName) {
        name = `${name}Item`;
      }
      let uniqueName = name;
      let counter = 1;
      while (interfaceNames.has(uniqueName)) {
        uniqueName = `${name}${counter}`;
        counter++;
      }
      interfaceNames.add(uniqueName);
      return uniqueName;
    };

    const determineType = (val: any, fieldName: string, depth: number = 0): string => {
      if (val === null) {
        return 'any';
      }

      const type = typeof val;
      if (type === 'string') return 'string';
      if (type === 'number') return 'number';
      if (type === 'boolean') return 'boolean';

      if (Array.isArray(val)) {
        if (val.length === 0) return 'any[]';

        const objectTypes = val.filter((item) => typeof item === 'object' && item !== null);
        if (objectTypes.length > 0) {
          const merged: any = {};
          objectTypes.forEach((item) => Object.assign(merged, item));
          
          if (!useInlineTypes) {
            const subName = getUniqueName(fieldName);
            const fields = parseObject(merged, depth);
            interfaces.push({ name: subName, fields });
            return `${subName}[]`;
          } else {
            const fields = parseObject(merged, depth);
            const indent = '  '.repeat(depth);
            const fieldIndent = '  '.repeat(depth + 1);
            const fieldsStr = fields
              .map((f) => `${fieldIndent}${f.name}${f.optional ? '?' : ''}: ${f.type};`)
              .join('\n');
            return `Array<{\n${fieldsStr}\n${indent}}>`;
          }
        }

        const itemTypes = new Set<string>();
        val.forEach((item) => {
          itemTypes.add(determineType(item, fieldName, depth));
        });

        if (itemTypes.size === 1) {
          const singleType = Array.from(itemTypes)[0];
          return `${singleType}[]`;
        }

        return `Array<${Array.from(itemTypes).join(' | ')}>`;
      }

      if (type === 'object') {
        if (!useInlineTypes) {
          const subName = getUniqueName(fieldName);
          const fields = parseObject(val, depth);
          interfaces.push({ name: subName, fields });
          return subName;
        } else {
          const fields = parseObject(val, depth);
          const indent = '  '.repeat(depth);
          const fieldIndent = '  '.repeat(depth + 1);
          const fieldsStr = fields
            .map((f) => `${fieldIndent}${f.name}${f.optional ? '?' : ''}: ${f.type};`)
            .join('\n');
          return `{\n${fieldsStr}\n${indent}}`;
        }
      }

      return 'any';
    };

    const parseObject = (obj: any, depth: number = 0): TsField[] => {
      if (typeof obj !== 'object' || obj === null) return [];
      const keys = Object.keys(obj);
      return keys.map((key) => {
        const raw = obj[key];
        const isOptional = useOptional && (raw === null || raw === undefined);
        const fieldType = determineType(raw, key, depth + 1);
        return { name: key, type: fieldType, optional: isOptional };
      });
    };

    if (parsed === null) {
      return { code: useTypeAlias ? `export type ${mainName} = any;` : `export interface ${mainName} {}` };
    }

    if (typeof parsed !== 'object') {
      const tsType = determineType(parsed, mainName, 0);
      return { code: `export type ${mainName} = ${tsType};` };
    }

    if (Array.isArray(parsed)) {
      if (parsed.length === 0) {
        return { code: `export type ${mainName} = any[];` };
      }
      const itemType = determineType(parsed[0], mainName, 0);
      let code = '';
      if (interfaces.length > 0) {
        interfaces.forEach((inf) => {
          const fieldsStr = inf.fields.map((f) => `  ${f.name}${f.optional ? '?' : ''}: ${f.type};`).join('\n');
          if (useTypeAlias) {
            code += `export type ${inf.name} = {\n${fieldsStr}\n};\n\n`;
          } else {
            code += `export interface ${inf.name} {\n${fieldsStr}\n}\n\n`;
          }
        });
      }
      // Alias format
      let arrayCode = '';
      if (itemType.startsWith('{') || itemType.startsWith('Array<') || itemType.includes('|')) {
        arrayCode = `Array<${itemType}>`;
      } else {
        arrayCode = `${itemType}[]`;
      }
      code += `export type ${mainName} = ${arrayCode};`;
      return { code: code.trim() };
    }

    // Process root object
    const mainFields = parseObject(parsed, 0);
    interfaces.unshift({ name: mainName, fields: mainFields });

    let code = '';
    interfaces.forEach((inf) => {
      const fieldsStr = inf.fields.map((f) => `  ${f.name}${f.optional ? '?' : ''}: ${f.type};`).join('\n');
      if (useTypeAlias) {
        code += `export type ${inf.name} = {\n${fieldsStr}\n};\n\n`;
      } else {
        code += `export interface ${inf.name} {\n${fieldsStr}\n}\n\n`;
      }
    });

    return { code: code.trim() };
  } catch (err: any) {
    return { code: '', error: err.message };
  }
}

export function JsonToTs() {
  const [inputJson, setInputJson] = useState(SAMPLE_JSON);
  const [outputTs, setOutputTs] = useState('');
  const [rootName, setRootName] = useState('AutoGenerated');
  const [useTypeAlias, setUseTypeAlias] = useState(false);
  const [useOptional, setUseOptional] = useState(true);
  const [useInlineTypes, setUseInlineTypes] = useState(false);
  const [status, setStatus] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [copyStatus, setCopyStatus] = useState<CopyStatus>('idle');

  const textToCopy = outputTs || inputJson;

  const handleGenerate = () => {
    const result = convertJsonToTypeScript(inputJson, rootName, useTypeAlias, useOptional, useInlineTypes);
    if (result.error) {
      setStatus({ type: 'error', message: `Parse failed: ${result.error}` });
      setOutputTs('');
    } else {
      setOutputTs(result.code);
      setStatus({ type: 'success', message: 'TypeScript interfaces generated.' });
      setCopyStatus('idle');
    }
  };

  const handleClear = () => {
    setInputJson('');
    setOutputTs('');
    setStatus(null);
    setCopyStatus('idle');
  };

  const handleLoadExample = () => {
    setInputJson(SAMPLE_JSON);
    setOutputTs('');
    setStatus(null);
    setCopyStatus('idle');
  };

  const handleCopy = () => {
    if (!textToCopy) return;

    const showCopyStatus = (nextStatus: CopyStatus) => {
      setCopyStatus(nextStatus);
      window.setTimeout(() => setCopyStatus('idle'), 1600);
    };

    const copyWithSelection = () => {
      try {
        const textarea = document.createElement('textarea');
        textarea.value = textToCopy;
        textarea.style.position = 'fixed';
        textarea.style.top = '0';
        textarea.style.left = '0';
        textarea.style.width = '1px';
        textarea.style.height = '1px';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.focus();
        textarea.select();
        const copied = document.execCommand('copy');
        document.body.removeChild(textarea);
        return copied;
      } catch (err) {
        console.error('Failed to copy TypeScript interfaces: ', err);
        return false;
      }
    };

    if (copyWithSelection()) {
      showCopyStatus('copied');
      return;
    }

    if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(textToCopy)
        .then(() => showCopyStatus('copied'))
        .catch(() => showCopyStatus('failed'));
      return;
    }

    showCopyStatus('failed');
  };

  const handleCopyKeyDown = (event: KeyboardEvent<HTMLButtonElement>) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      handleCopy();
    }
  };

  return (
    <div className="json-to-ts-tool-container">
      {copyStatus !== 'idle' && (
        <div className={`json-to-ts-toast ${copyStatus === 'failed' ? 'is-failed' : ''}`}>
          {copyStatus === 'copied' ? 'Copied to clipboard' : 'Clipboard blocked'}
        </div>
      )}

      <div className="json-to-ts-heading">
        <div>
          <p className="tool-kicker">Code Generator</p>
          <h1>JSON to TypeScript Interfaces</h1>
          <p>Convert JSON schemas or payloads into clean TypeScript interface or type declarations.</p>
        </div>
      </div>

      <div className="json-to-ts-control-card">
        <label>
          Root Interface Name
          <input
            type="text"
            value={rootName}
            onChange={(event) => setRootName(event.target.value)}
            placeholder="AutoGenerated"
          />
        </label>

        <label className="json-to-ts-check">
          <input
            type="checkbox"
            checked={useOptional}
            onChange={(event) => setUseOptional(event.target.checked)}
          />
          Optional fields for nulls
        </label>

        <label className="json-to-ts-check">
          <input
            type="checkbox"
            checked={useTypeAlias}
            onChange={(event) => setUseTypeAlias(event.target.checked)}
          />
          Use Type Alias
        </label>

        <label className="json-to-ts-check">
          <input
            type="checkbox"
            checked={useInlineTypes}
            onChange={(event) => setUseInlineTypes(event.target.checked)}
          />
          Inline nested types
        </label>
      </div>

      <div className="json-to-ts-panels">
        <div className="json-to-ts-panel">
          <div className="json-to-ts-panel-header">
            <h3>JSON Payload</h3>
            <p>Paste valid JSON payload</p>
          </div>
          <CodeEditor
            value={inputJson}
            onChange={setInputJson}
            placeholder="Paste raw JSON here..."
            language="json"
          />
        </div>

        <div className="json-to-ts-panel">
          <div className="json-to-ts-panel-header">
            <h3>TypeScript Code</h3>
            <p>Generated interfaces or types</p>
          </div>
          <CodeEditor
            value={outputTs}
            onChange={setOutputTs}
            placeholder="Generated TypeScript interfaces will appear here..."
            language="typescript"
          />
        </div>
      </div>

      <div className="json-to-ts-action-row">
        <button onClick={handleGenerate} className="btn btn-primary" disabled={!inputJson.trim()}>
          Generate TS Interfaces
        </button>
        <button
          type="button"
          onMouseDown={(event) => {
            event.preventDefault();
            handleCopy();
          }}
          onKeyDown={handleCopyKeyDown}
          className="btn btn-secondary"
          disabled={!textToCopy}
        >
          {copyStatus === 'copied' ? 'Copied' : 'Copy'}
        </button>
        <button onClick={handleLoadExample} className="btn btn-secondary">
          Load Example
        </button>
        <button onClick={handleClear} className="btn btn-danger">
          Clear
        </button>
        {status && <span className={`json-to-ts-status is-${status.type}`}>{status.message}</span>}
      </div>
    </div>
  );
}
