import { type KeyboardEvent, useState } from 'react';
import { CodeEditor } from '../common/CodeEditor';
import './JsonToGo.css';

type CopyStatus = 'idle' | 'copied' | 'failed';

const SAMPLE_JSON = `{
  "id": 1,
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
  "active": true,
  "skills": ["Golang", "TypeScript", "SQL"],
  "address": {
    "street": "456 Market St",
    "city": "San Francisco",
    "zip": "94103"
  },
  "roles": [
    { "role_id": "admin", "permissions": ["read", "write"] },
    { "role_id": "billing", "permissions": ["read"] }
  ]
}`;

const initialisms = new Set(['id', 'uuid', 'url', 'api', 'ip', 'http', 'https', 'json', 'xml', 'sql']);

const toPascalCase = (str: string) => {
  const cleaned = str.replace(/[^a-zA-Z0-9_]/g, '_');
  return cleaned
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((part) => {
      const lower = part.toLowerCase();
      if (initialisms.has(lower)) return lower.toUpperCase();
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('') || 'Field';
};

const singularizeName = (name: string): string => {
  let sing = name;
  if (sing.endsWith('ies')) {
    sing = sing.slice(0, -3) + 'y';
  } else if (sing.endsWith('ses')) {
    sing = sing.slice(0, -2);
  } else if (sing.endsWith('s') && !sing.endsWith('ss')) {
    sing = sing.slice(0, -1);
  }
  return sing;
};

interface GoField {
  name: string;
  type: string;
  tag: string;
}

interface StructDefinition {
  name: string;
  fields: GoField[];
}

function convertJsonToGo(
  jsonStr: string,
  rootName: string = 'AutoGenerated',
  usePointers: boolean = false,
  useInlineStructs: boolean = false,
): { code: string; error?: string } {
  try {
    const trimmed = jsonStr.trim();
    if (!trimmed) {
      return { code: '' };
    }
    const parsed = JSON.parse(trimmed);

    const structs: StructDefinition[] = [];
    const structNames = new Set<string>();

    const mainStructName = toPascalCase(rootName || 'AutoGenerated');
    structNames.add(mainStructName);

    const getUniqueStructName = (baseName: string): string => {
      let name = toPascalCase(singularizeName(baseName));
      if (!name) name = 'Struct';
      
      // If matches main root struct name, append "Item" or "Sub"
      if (name === mainStructName) {
        name = `${name}Item`;
      }

      let uniqueName = name;
      let counter = 1;
      while (structNames.has(uniqueName)) {
        uniqueName = `${name}${counter}`;
        counter++;
      }
      structNames.add(uniqueName);
      return uniqueName;
    };

    const determineGoType = (val: any, fieldName: string): string => {
      if (val === null) {
        return 'interface{}';
      }

      const type = typeof val;
      if (type === 'string') {
        return 'string';
      }
      if (type === 'number') {
        return Number.isInteger(val) ? 'int' : 'float64';
      }
      if (type === 'boolean') {
        return 'bool';
      }

      if (Array.isArray(val)) {
        if (val.length === 0) {
          return '[]interface{}';
        }

        const types = new Set<string>();
        val.forEach((item) => {
          types.add(determineGoType(item, fieldName));
        });

        if (types.size === 1) {
          const singleType = Array.from(types)[0];
          return `[]${singleType}`;
        }

        // Merge array of objects if applicable
        const objectTypes = val.filter((item) => typeof item === 'object' && item !== null);
        if (objectTypes.length > 0) {
          const mergedObj: any = {};
          objectTypes.forEach((item) => {
            Object.assign(mergedObj, item);
          });
          if (!useInlineStructs) {
            const structName = getUniqueStructName(fieldName);
            const fields = parseObjectFields(mergedObj);
            structs.push({ name: structName, fields });
            return `[]${structName}`;
          } else {
            const fields = parseObjectFields(mergedObj);
            const fieldsStr = fields
              .map((f) => `\t${f.name} ${f.type} ${f.tag}`)
              .join('\n');
            return `[]struct {\n${fieldsStr}\n}`;
          }
        }

        return '[]interface{}';
      }

      if (type === 'object') {
        if (!useInlineStructs) {
          const structName = getUniqueStructName(fieldName);
          const fields = parseObjectFields(val);
          structs.push({ name: structName, fields });
          return usePointers ? `*${structName}` : structName;
        } else {
          const fields = parseObjectFields(val);
          const fieldsStr = fields
            .map((f) => `\t${f.name} ${f.type} ${f.tag}`)
            .join('\n');
          const inlineStruct = `struct {\n${fieldsStr}\n}`;
          return usePointers ? `*${inlineStruct}` : inlineStruct;
        }
      }

      return 'interface{}';
    };

    const parseObjectFields = (obj: any): GoField[] => {
      if (typeof obj !== 'object' || obj === null) return [];
      const keys = Object.keys(obj);
      return keys.map((key) => {
        const goFieldName = toPascalCase(key);
        const rawVal = obj[key];
        const valType = determineGoType(rawVal, key);
        const isPointer = usePointers && rawVal === null;
        const finalType = isPointer ? `*${valType}` : valType;
        const tag = `\`json:"${key}"\``;
        return { name: goFieldName, type: finalType, tag };
      });
    };

    if (parsed === null) {
      return { code: `type ${mainStructName} interface{}` };
    }

    if (typeof parsed !== 'object') {
      const goType = determineGoType(parsed, mainStructName);
      return { code: `type ${mainStructName} ${goType}` };
    }

    if (Array.isArray(parsed)) {
      if (parsed.length === 0) {
        return { code: `type ${mainStructName} []interface{}` };
      }
      const itemType = determineGoType(parsed[0], mainStructName);
      let outputCode = '';
      if (structs.length > 0) {
        structs.forEach((s) => {
          const fieldsStr = s.fields.map((f) => `\t${f.name} ${f.type} ${f.tag}`).join('\n');
          outputCode += `type ${s.name} struct {\n${fieldsStr}\n}\n\n`;
        });
      }
      // Trim slice brackets for alias
      const normalizedItemType = itemType.startsWith('[]') ? itemType : itemType;
      outputCode += `type ${mainStructName} []${normalizedItemType}`;
      return { code: outputCode.trim() };
    }

    // Process root object
    const mainFields = parseObjectFields(parsed);
    structs.unshift({ name: mainStructName, fields: mainFields });

    let outputCode = '';
    structs.forEach((s) => {
      const fieldsStr = s.fields.map((f) => `\t${f.name} ${f.type} ${f.tag}`).join('\n');
      outputCode += `type ${s.name} struct {\n${fieldsStr}\n}\n\n`;
    });

    return { code: outputCode.trim() };
  } catch (err: any) {
    return { code: '', error: err.message };
  }
}

export function JsonToGo() {
  const [inputJson, setInputJson] = useState(SAMPLE_JSON);
  const [outputGo, setOutputGo] = useState('');
  const [rootName, setRootName] = useState('AutoGenerated');
  const [usePointers, setUsePointers] = useState(false);
  const [useInlineStructs, setUseInlineStructs] = useState(false);
  const [status, setStatus] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [copyStatus, setCopyStatus] = useState<CopyStatus>('idle');

  const textToCopy = outputGo || inputJson;

  const handleGenerate = () => {
    const result = convertJsonToGo(inputJson, rootName, usePointers, useInlineStructs);
    if (result.error) {
      setStatus({ type: 'error', message: `Parse failed: ${result.error}` });
      setOutputGo('');
    } else {
      setOutputGo(result.code);
      setStatus({ type: 'success', message: 'Go structs generated.' });
      setCopyStatus('idle');
    }
  };

  const handleClear = () => {
    setInputJson('');
    setOutputGo('');
    setStatus(null);
    setCopyStatus('idle');
  };

  const handleLoadExample = () => {
    setInputJson(SAMPLE_JSON);
    setOutputGo('');
    setStatus(null);
    setCopyStatus('idle');
  };

  const handleCopy = () => {
    if (!textToCopy) return;

    const showCopyStatus = (nextStatus: CopyStatus) => {
      setCopyStatus(nextStatus);
      window.setTimeout(() => setCopyStatus('idle'), 1600);
    };

    const copyWithSelection = () => {
      try {
        const textarea = document.createElement('textarea');
        textarea.value = textToCopy;
        textarea.style.position = 'fixed';
        textarea.style.top = '0';
        textarea.style.left = '0';
        textarea.style.width = '1px';
        textarea.style.height = '1px';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.focus();
        textarea.select();
        const copied = document.execCommand('copy');
        document.body.removeChild(textarea);
        return copied;
      } catch (err) {
        console.error('Failed to copy text: ', err);
        return false;
      }
    };

    if (copyWithSelection()) {
      showCopyStatus('copied');
      return;
    }

    if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(textToCopy)
        .then(() => showCopyStatus('copied'))
        .catch(() => showCopyStatus('failed'));
      return;
    }

    showCopyStatus('failed');
  };

  const handleCopyKeyDown = (event: KeyboardEvent<HTMLButtonElement>) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      handleCopy();
    }
  };

  return (
    <div className="json-to-go-tool-container">
      {copyStatus !== 'idle' && (
        <div className={`json-to-go-toast ${copyStatus === 'failed' ? 'is-failed' : ''}`}>
          {copyStatus === 'copied' ? 'Copied to clipboard' : 'Clipboard blocked'}
        </div>
      )}

      <div className="json-to-go-heading">
        <div>
          <p className="tool-kicker">Code Generator</p>
          <h1>JSON to Go Struct</h1>
          <p>Convert JSON schemas or objects into Go struct definitions instantly.</p>
        </div>
      </div>

      <div className="json-to-go-control-card">
        <label>
          Root Struct Name
          <input
            type="text"
            value={rootName}
            onChange={(event) => setRootName(event.target.value)}
            placeholder="AutoGenerated"
          />
        </label>

        <label className="json-to-go-check">
          <input
            type="checkbox"
            checked={usePointers}
            onChange={(event) => setUsePointers(event.target.checked)}
          />
          Pointers for nulls
        </label>

        <label className="json-to-go-check">
          <input
            type="checkbox"
            checked={useInlineStructs}
            onChange={(event) => setUseInlineStructs(event.target.checked)}
          />
          Inline nested structs
        </label>
      </div>

      <div className="json-to-go-panels">
        <div className="json-to-go-panel">
          <div className="json-to-go-panel-header">
            <h3>JSON Payload</h3>
            <p>Paste valid JSON payload</p>
          </div>
          <CodeEditor
            value={inputJson}
            onChange={setInputJson}
            placeholder="Paste raw JSON here..."
            language="json"
          />
        </div>

        <div className="json-to-go-panel">
          <div className="json-to-go-panel-header">
            <h3>Go Structs</h3>
            <p>Go struct definition result</p>
          </div>
          <CodeEditor
            value={outputGo}
            onChange={setOutputGo}
            placeholder="Generated Go structs will appear here..."
            language="go"
          />
        </div>
      </div>

      <div className="json-to-go-action-row">
        <button onClick={handleGenerate} className="btn btn-primary" disabled={!inputJson.trim()}>
          Generate Go Struct
        </button>
        <button
          type="button"
          onMouseDown={(event) => {
            event.preventDefault();
            handleCopy();
          }}
          onKeyDown={handleCopyKeyDown}
          className="btn btn-secondary"
          disabled={!textToCopy}
        >
          {copyStatus === 'copied' ? 'Copied' : 'Copy'}
        </button>
        <button onClick={handleLoadExample} className="btn btn-secondary">
          Load Example
        </button>
        <button onClick={handleClear} className="btn btn-danger">
          Clear
        </button>
        {status && <span className={`json-to-go-status is-${status.type}`}>{status.message}</span>}
      </div>
    </div>
  );
}
